export const REPLACEMENT_PRICING = {
  prologis_texas: {
    recover_tpo: 6.0,
    recover_bur_gravel: 6.25,
    tearoff_two_new_tpo: 10.0,
    tearoff_two_fully_adhered: 12.0,
    tpo_infill_over_metal: 8.25,
    spud_torch_2ply_over_bur: 9.0,
    epdm_membrane_swap: 6.0,
    adder_fully_adhered_over_steel: 2.0,
    adder_loadmasters: 3.0,
  },
  non_prologis_texas: {
    recover_tpo_bur_smooth_modbit: 5.75,
    recover_bur_gravel: 6.5,
    tpo_infill_over_metal: 7.5,
    tearoff_two_new_tpo: 10.0,
    epdm_membrane_swap: 6.0,
    eastgroup_hou_recover: 6.5,
    eastgroup_hou_tearoff: 9.0,
  },
  non_prologis_general: {
    recover_tpo_bur_smooth_modbit: 5.25,
    recover_bur_gravel: 5.5,
    tpo_infill_over_metal: 7.0,
    tearoff_two_roofs: 10.25,
    epdm_membrane_swap: 4.75,
    spud_torch_2ply_over_bur: 9.0,
    adder_loadmasters: 3.0,
    adder_fully_adhered: 2.0,
  },
} as const

export const REPAIR_PRICING: Record<string, { unit: string; price: number; notes: string }[]> = {
  tpo_single_ply: [
    { unit: "ea", price: 138, notes: "fill pitch pan" },
    { unit: "ea", price: 350, notes: "reflash scupper" },
    { unit: "ea", price: 1800, notes: "reflash 6x5 curb" },
    { unit: "ea", price: 165, notes: "small patch" },
    { unit: "lf", price: 35, notes: "reflash expansion joint" },
    { unit: "lf", price: 30, notes: "new edge metal" },
    { unit: "ea", price: 210, notes: "flash pipe or AC stand" },
  ],
  epdm: [
    { unit: "ea", price: 138, notes: "fill pitch pan" },
    { unit: "ea", price: 165, notes: "seal hole or tear" },
    { unit: "lf", price: 33, notes: "reflash walls or curbs" },
    { unit: "ea", price: 77, notes: "reseal expansion joint seams" },
    { unit: "lf", price: 22, notes: "clean and reseal open seam" },
  ],
  bur_gravel: [
    { unit: "ea", price: 2065, notes: "flash 6x5 curb" },
    { unit: "ea", price: 275, notes: "flash pipe or AC stand with permaflash" },
    { unit: "ea", price: 88, notes: "fill pitch pan" },
    { unit: "ea", price: 100, notes: "seal open base flashing under 5 items" },
    { unit: "ea", price: 50, notes: "seal open base flashing 5 plus items" },
    { unit: "lf", price: 40, notes: "encapsulate expansion joint over 100 lf" },
    { unit: "lf", price: 70, notes: "encapsulate expansion joint under 100 lf" },
    { unit: "lf", price: 55, notes: "new gravel stop" },
    { unit: "ea", price: 55, notes: "clean and reseal storm collars on pipes" },
  ],
  bur_cap_sheet_modbit: [
    { unit: "lf", price: 33, notes: "seal expansion bellows" },
    { unit: "lf", price: 55, notes: "new gravel stop" },
    { unit: "ea", price: 88, notes: "fill pitch pan" },
    { unit: "lf", price: 40, notes: "seal base flashing over 100 lf" },
    { unit: "lf", price: 70, notes: "seal base flashing under 100 lf" },
    { unit: "lf", price: 73, notes: "replace wall flashing" },
    { unit: "ea", price: 150, notes: "patch blister" },
    { unit: "ea", price: 550, notes: "reflash scupper" },
    { unit: "ea", price: 3300, notes: "new drain" },
    { unit: "ea", price: 95, notes: "fill pitch pan cap sheet" },
  ],
  sheet_metal: [
    { unit: "lf", price: 60, notes: "replace gutter over 50 lf" },
    { unit: "lf", price: 80, notes: "replace gutter under 50 lf" },
    { unit: "lf", price: 33, notes: "seal coping joints" },
    { unit: "lf", price: 77, notes: "replace coping cap" },
    { unit: "lf", price: 8, notes: "clean and caulk counterflashing" },
    { unit: "lf", price: 10, notes: "new counterflashing" },
    { unit: "lf", price: 28, notes: "replace counterflashing" },
    { unit: "ea", price: 850, notes: "clean gutter half day" },
    { unit: "ea", price: 1700, notes: "clean gutter full day" },
    { unit: "ea", price: 110, notes: "seal laps" },
    { unit: "lf", price: 17, notes: "clean prime and paint rusted areas of gutter" },
    { unit: "ea", price: 55, notes: "replace downspout" },
  ],
  skylights: [
    { unit: "ea", price: 1045, notes: "replace 4x4 dome" },
    { unit: "ea", price: 2035, notes: "replace 4x8 dome" },
    { unit: "ea", price: 4500, notes: "replace 4x8 melt out" },
    { unit: "ea", price: 5500, notes: "replace 4x8 spring loaded" },
    { unit: "ea", price: 165, notes: "reseal skylight" },
    { unit: "ea", price: 1000, notes: "new safety fall protection" },
    { unit: "ea", price: 800, notes: "new walk pads" },
  ],
  misc: [
    { unit: "ea", price: 165, notes: "HVAC service door" },
    { unit: "ea", price: 55, notes: "reseal storm collars" },
    { unit: "ea", price: 195, notes: "seal tilt wall joint" },
    { unit: "ea", price: 550, notes: "replace drain strainer" },
    { unit: "ea", price: 550, notes: "remove trash" },
    { unit: "ea", price: 25, notes: "seal conduit" },
    { unit: "ea", price: 14000, notes: "exterior wall ladder min" },
    { unit: "ea", price: 22000, notes: "exterior wall ladder max" },
  ],
}
